# Data Inference

In [1]:
import pickle
import pandas as pd
import numpy as np

In [2]:
# Load All Files

with open('model_scaler_cluster.pkl', 'rb') as file_1:
  model_scaler = pickle.load(file_1)

with open('model_kmeans.pkl', 'rb') as file_2:
  model_kmeans = pickle.load(file_2)

with open('model_pca.pkl', 'rb') as file_3:
  model_pca = pickle.load(file_3)

Memasukan model scaling,model K-means,dan model pca kedalam file data inference

In [13]:
# membuat data dummy dengan 1000 baris random
np.random.seed(1)
ship_mode = np.random.choice(['Standard Class', 'Second Class', 'First Class', 'Same Day'], size=1000)
product_category = np.random.choice(['Fashion', 'Home & Furniture', 'Auto & Accessories', 'Electronic'], size=1000)
region = np.random.choice([
    'Central', 'South', 'EMEA', 'North', 'Africa', 'Oceania',
    'West', 'Southeast Asia', 'East', 'North Asia', 'Central Asia',
    'Caribbean', 'Canada', 'So3th','4orth'
], size=1000)
months = np.random.choice( [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
], size=1000)
order_priority = np.random.choice(['Medium', 'High', 'Critical', 'Low'], size=1000)
aging = np.random.uniform(0,47137,1000)
sales = np.random.uniform(0,1,1000)
quantity = np.random.uniform(0,1,1000)
discount = np.random.uniform(0,1,1000)
shipping_cost = np.random.uniform(0,1.5,1000)

Saya tidak memasukan kolom tenure karena tidak dimasukan kedalam proses PCA dan model kmeans clustering.

Membuat data dummy untuk menguji model K-Means.

In [14]:
# Membuat DataFrame
data_inf = pd.DataFrame({
    'BALANCE' : BALANCE,
    'BALANCE_FREQUENCY': BALANCE_FREQUENCY,
    'PURCHASES': PURCHASES,
    'ONEOFF_PURCHASES': ONEOFF_PURCHASES,
    'INSTALLMENTS_PURCHASES' : INSTALLMENTS_PURCHASES,
    'CASH_ADVANCE': CASH_ADVANCE,
    'PURCHASES_FREQUENCY': PURCHASES_FREQUENCY,
    'ONEOFF_PURCHASES_FREQUENCY': ONEOFF_PURCHASES_FREQUENCY,
    'PURCHASES_INSTALLMENTS_FREQUENCY' : PURCHASES_INSTALLMENTS_FREQUENCY,
    'CASH_ADVANCE_FREQUENCY': CASH_ADVANCE_FREQUENCY,
    'CASH_ADVANCE_TRX': CASH_ADVANCE_TRX,
    'PURCHASES_TRX': PURCHASES_TRX,
    'CREDIT_LIMIT': CREDIT_LIMIT,
    'PAYMENTS': PAYMENTS,
    'MINIMUM_PAYMENTS': MINIMUM_PAYMENTS,
    'PRC_FULL_PAYMENT': PRC_FULL_PAYMENT,
    
})

data_inf

,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT
0,7712.821977,0.325810,23684.940598,32234.521403,5270.012850,31994.497415,0.657568,0.177031,0.364664,0.361341,94.156126,86.789856,1337.347236,13849.043589,23046.045583,0.946857
1,13322.401506,0.889827,35934.707713,1457.554548,9600.994125,36022.193398,0.909170,0.401756,0.672750,0.817852,37.905251,0.548668,17433.154605,24614.484723,34437.635491,0.574356
2,2.115362,0.751708,24981.611188,7773.763041,8320.961421,1519.067069,0.901952,0.002941,0.553076,0.191061,90.451480,74.545482,3950.368644,1354.439725,21574.332685,0.527748
3,5591.640931,0.762632,10330.625929,39708.154848,500.886846,46301.318891,0.390855,0.400597,0.406415,0.112171,99.900404,122.632325,7944.487734,14289.131903,61890.327965,0.045415
4,2714.250201,0.469479,12156.133360,39031.429760,13521.318737,4304.679986,0.612539,0.893202,0.397959,1.245916,29.113402,2.672798,21357.379901,636.111154,54282.936526,0.520923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,18021.592158,0.447508,34325.033960,28817.600878,4146.598591,1138.236794,0.838440,0.268903,0.575273,1.041996,105.495191,239.856214,27934.334347,30791.245382,54647.770984,0.412978
996,5764.945463,0.184128,8790.731262,13239.715860,7603.753621,41541.847729,0.304822,0.479355,0.575614,0.444347,106.260702,1.527264,2588.689714,22452.581574,68803.413997,0.926945
997,12369.393227,0.828733,18043.080143,2983.433319,4819.395788,1234.566090,0.353098,0.674659,0.583473,0.089301,122.798005,112.421204,28040.002208,4520.036384,52879.462507,0.433003
998,6028.763499,0.030998,6915.979686,23551.237799,14565.591824,44819.178932,0.730641,0.684231,0.920230,0.162065,108.388000,113.329372,25375.900980,23058.853482,13811.664283,0.058909
999,14323.957035,0.946728,21719.029989,29798.395350,3676.150349,26864.207909,0.777833,0.821391,0.533101,1.144191,42.973202,238.134485,28850.980942,27695.751687,73407.664766,0.887553

In [15]:
scaled = model_scaler.fit_transform(data_inf)

In [16]:
pca1 = model_pca.fit_transform(scaled)

Melakukan reduksi dimensi pada data dummy untuk dimasukan kedalam model

In [17]:
# melihat isi data
pca1

array([[-0.45970177, -0.31603248,  0.27458421, ..., -0.5407814 ,
        -0.03303827,  0.06163068],
       [-0.33801084, -0.25413228, -0.16065929, ...,  0.07317872,
        -0.06962376, -0.19851587],
       [-0.43573097,  0.01214326, -0.5067913 , ..., -0.4854225 ,
        -0.60678299,  0.3219352 ],
       ...,
       [ 0.19410855, -0.33938629, -0.82572087, ..., -0.35995567,
        -0.34274476, -0.00536056],
       [-0.65435821, -0.05600743, -0.44816098, ...,  0.55658712,
        -0.05058286, -0.18565157],
       [ 0.52067514,  0.03214077,  0.03409825, ..., -0.02509615,
         0.24369609, -0.3772061 ]])

In [18]:
# Predict Inference-Set

cluster_inf = model_kmeans.predict(pca1)
cluster_inf

array([1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 2, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 2,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 2, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 2, 1, 2, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 2, 1, 0, 1, 1, 1, 2, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 2, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 2, 1, 0, 1, 1, 0, 1, 0, 2, 1, 0,
       1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 2, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 2, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 2, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 2,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 2, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 2, 1, 0, 0, 1, 1, 1,
       2, 1, 0, 0, 1, 0, 1, 0, 0, 2, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 1, 1, 0, 0, 1, 0, 2,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 2, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 2, 0, 1, 1, 0, 1, 1, 1, 0, 2, 0, 2, 1, 1, 1, 0, 0,
       2, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 2, 1, 2, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 2, 1, 1, 0, 0, 0, 0, 2,
       1, 2, 2, 0, 2, 0, 1, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 2, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 0, 0, 1, 1, 2, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 2, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 2, 0, 1, 0, 1, 1, 1, 1, 2, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 2, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 2, 1, 1, 0, 1, 2, 0, 2, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 2, 2, 0, 0, 1, 0, 1, 0, 1, 2, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 2, 0, 0, 1, 0, 1, 2, 1, 1, 2, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 2, 2, 1, 1, 0, 1, 2, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       2, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 2, 2, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 2, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 2, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [19]:
# Convert into DataFrame

cluster_inf_df = pd.DataFrame(cluster_inf, columns=['Cluster - Prediction'])
cluster_inf_df

     Cluster - Prediction
0                       1
1                       1
2                       1
3                       1
4                       0
..                    ...
995                     0
996                     1
997                     0
998                     1
999                     0

[1000 rows x 1 columns]

Membuat kolom dataframe baru untuk melihat hasil prediksi

In [20]:
# Merge Inference-Set and Prediction

tabel_inference = pd.concat([data_inf, cluster_inf_df], axis=1)
tabel_inference

,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,Cluster - Prediction
0,7712.821977,0.325810,23684.940598,32234.521403,5270.012850,31994.497415,0.657568,0.177031,0.364664,0.361341,94.156126,86.789856,1337.347236,13849.043589,23046.045583,0.946857,1
1,13322.401506,0.889827,35934.707713,1457.554548,9600.994125,36022.193398,0.909170,0.401756,0.672750,0.817852,37.905251,0.548668,17433.154605,24614.484723,34437.635491,0.574356,1
2,2.115362,0.751708,24981.611188,7773.763041,8320.961421,1519.067069,0.901952,0.002941,0.553076,0.191061,90.451480,74.545482,3950.368644,1354.439725,21574.332685,0.527748,1
3,5591.640931,0.762632,10330.625929,39708.154848,500.886846,46301.318891,0.390855,0.400597,0.406415,0.112171,99.900404,122.632325,7944.487734,14289.131903,61890.327965,0.045415,1
4,2714.250201,0.469479,12156.133360,39031.429760,13521.318737,4304.679986,0.612539,0.893202,0.397959,1.245916,29.113402,2.672798,21357.379901,636.111154,54282.936526,0.520923,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,18021.592158,0.447508,34325.033960,28817.600878,4146.598591,1138.236794,0.838440,0.268903,0.575273,1.041996,105.495191,239.856214,27934.334347,30791.245382,54647.770984,0.412978,0
996,5764.945463,0.184128,8790.731262,13239.715860,7603.753621,41541.847729,0.304822,0.479355,0.575614,0.444347,106.260702,1.527264,2588.689714,22452.581574,68803.413997,0.926945,1
997,12369.393227,0.828733,18043.080143,2983.433319,4819.395788,1234.566090,0.353098,0.674659,0.583473,0.089301,122.798005,112.421204,28040.002208,4520.036384,52879.462507,0.433003,0
998,6028.763499,0.030998,6915.979686,23551.237799,14565.591824,44819.178932,0.730641,0.684231,0.920230,0.162065,108.388000,113.329372,25375.900980,23058.853482,13811.664283,0.058909,1
999,14323.957035,0.946728,21719.029989,29798.395350,3676.150349,26864.207909,0.777833,0.821391,0.533101,1.144191,42.973202,238.134485,28850.980942,27695.751687,73407.664766,0.887553,0

Menggabungkan cluster dengan data dummy untuk memudahkan kita melihat cluster segmentation pelanggan

**Melihat pelanggan yang sering melakukan pembayaran dengan cicilan dan jumlah pembayaran yang dilakukan pelanggan terbesar**

In [21]:
tabel_inference[(tabel_inference['PAYMENTS'] >  50000) & (tabel_inference['PURCHASES_INSTALLMENTS_FREQUENCY'] > 0.9)]

,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,Cluster - Prediction
870,980.134067,0.766862,1048.420484,19965.864286,2711.299424,40649.780443,0.333011,0.808717,0.925039,0.674582,10.735696,121.027643,23292.611762,50649.108172,63344.89185,0.081894,1

Terlihat jika pelanggan itu adalah sultan maka masuk kedalam cluster 2.